import {Game,distance} from './guard-core.mjs';
import {createRenderer} from './guard-view.mjs';
import {W,H,CORE,HEROES,BUILDINGS,WAVES,GEAR,RARITIES,SLOTS,TEXT} from './guard-content.mjs';
const $=id=>document.getElementById(id),SAVE='crystalGuard.run.v1',PREF='crystalGuard.preferences.v1';
const storage={get(k){try{return JSON.parse(localStorage.getItem(k));}catch{return null;}},set(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true;}catch{return false;}},remove(k){try{localStorage.removeItem(k);}catch{}}};
let preferences=storage.get(PREF)||{},lang=new URLSearchParams(location.search).get('lang')||preferences.lang||'zh';if(!['zh','en'].includes(lang))lang='zh';
const restored=Game.restore(storage.get(SAVE));let game=restored||new Game(),selected='knight',tool='move',paused=false,speed=1,sound=!!preferences.sound,loaded=false,lastPhase='',lastWave=-1,lastHUDPhase='',toastUntil=0,uiTime=0,lastKills=0;
const renderer=await createRenderer($('field'));const thumbs=new Map();
const strings={title:['琉璃城','Crystal Vanguard'],fit:['全景','Fit'],loading:['準備素材中…','Preparing the forest…'],party:['冒險者小隊','ADVENTURERS'],inventory:['裝備背包','Equipment'],build:['建造與防守','BUILD & DEFEND'],buildLive:['戰鬥中也能建造','Build during combat'],paused:['戰術暫停','TACTICAL PAUSE'],breathe:['想好下一步，再出發。','Take a breath. Find your next move.'],resume:['繼續守城','Resume defense'],introTitle:['在森林裡，守住一束光。','A little forest. A light to protect.'],introDesc:['四位冒險者、一顆水晶，以及你親手蓋起的防線。守過十二波敵襲，每一波都刷出新的可能。','Four adventurers, one crystal, and a defense you build yourself. Survive twelve waves and find a new build along the way.'],step1:['蓋起防線','Build your defense'],step1desc:['木柵改路、箭塔輸出、冰霜減速。戰鬥中隨時補建。','Walls reroute, towers attack, frost slows. Keep building during combat.'],step2:['指揮英雄','Command your heroes'],step2desc:['選角色再點地面調動；點敵人集火，按技能救場。','Select a hero and tap ground to move. Tap enemies to focus fire. Use skills to turn the tide.'],step3:['逐波刷裝','Find your build'],step3desc:['每波三選一裝備，組出吸血、穿透或冰凍流派。','Choose one of three items each wave: lifesteal, piercing, frost and more.'],runRule:['裝備只屬於這次冒險。重新開局會重置；離開後可接續最近的波次準備點。','Gear belongs to this run. New runs start fresh. Return later to your latest between-wave checkpoint.'],begin:['踏入森林','Enter the forest'],lootEyebrow:['戰利品 · 三選一','SPOILS · CHOOSE ONE'],buildYourParty:['讓裝備決定打法。','Let your gear shape the battle.'],spare:['備用裝備','Backpack'],bagNote:['波次之間換裝。替換下來的裝備會回到背包；分解可換建材金幣。','Change gear between waves. Replaced items return to your bag. Salvage spare gear for building gold.'],freshRule:['下一次冒險從零開始，試試另一種裝備與防線組合。','Your next adventure starts fresh. Try another combination of gear and defenses.'],again:['開始新的冒險','Start a fresh adventure'],restartTitle:['重新出發？','Start over?'],restartDesc:['這次冒險的裝備、建築與波次會重置。','This run’s gear, buildings and waves will reset.'],cancel:['繼續這次冒險','Keep this adventure']};
const t=v=>TEXT(v,lang),tr=k=>t(strings[k]||k);
function save(){const point=game.checkpoint();if(point&&!storage.set(SAVE,point))toast(t(['此瀏覽器無法儲存，離開後進度不會保留。','Storage unavailable: this run will not persist after leaving.']));}
function pref(){storage.set(PREF,{lang,sound});}
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');toastUntil=performance.now()+3000;}
let audio;function chime(type='click'){if(!sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const now=audio.currentTime,freq=type==='loot'?660:type==='skill'?440:type==='build'?330:510;const notes=type==='loot'?[1,1.25,1.5]:[1];notes.forEach((v,i)=>{const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.value=freq*v;o.connect(g);g.connect(audio.destination);g.gain.setValueAtTime(0,now+i*.09);g.gain.linearRampToValueAtTime(.035,now+i*.09+.012);g.gain.exponentialRampToValueAtTime(.001,now+i*.09+.22);o.start(now+i*.09);o.stop(now+i*.09+.25);});}catch{sound=false;}}
function thumb(index){if(thumbs.has(index))return thumbs.get(index);const f=renderer.frames[index];if(!f)return '';const c=document.createElement('canvas');c.width=96;c.height=108;const ctx=c.getContext('2d'),scale=Math.min(88/f.w,102/f.h);ctx.drawImage(renderer.atlas,f.x,f.y,f.w,f.h,48-f.w*scale/2,106-f.h*scale,f.w*scale,f.h*scale);const url=c.toDataURL();thumbs.set(index,url);return url;}
function staticUI(){document.documentElement.lang=lang==='zh'?'zh-Hant':'en';document.title=t(['琉璃城 · 森林守望','Crystal Vanguard · Forest Watch']);document.querySelectorAll('[data-i18n]').forEach(e=>e.textContent=tr(e.dataset.i18n));$('lang').textContent=lang==='zh'?'EN':'中文';$('sound').textContent=sound?'♪':'♪̸';$('sound').title=t(sound?['音效：開','Sound on']:['音效：關','Sound off']);$('pause').title=t(['暫停 / 繼續（P）','Pause / resume (P)']);$('sound').setAttribute('aria-pressed',String(sound));$('help').title=t(['玩法說明','How to play']);$('party').innerHTML=HEROES.map((h,i)=>`<button class="hero-button" data-hero="${h.id}" title="${t(h.job)} · ${t(h.desc)} (${i+1})"><img src="${thumb(h.sprite)}" alt=""><span><b>${t(h.name)}</b><small>${t(h.job)}</small></span><span class="mini-hp"><i></i></span></button>`).join('');
 $('build-tools').innerHTML=Object.entries(BUILDINGS).map(([id,b],i)=>`<button class="build-tool" data-tool="${id}" title="${t(b.name)} · ${t(b.desc)}"><small>${b.cost||'↩'}</small>${b.sprite!=null?`<img src="${thumb(b.sprite)}" alt="">`:`<span class="tool-glyph">${{repair:'⚒',upgrade:'↑',sell:'×'}[id]}</span>`}<b>${t(b.name)}</b></button>`).join('');renderer.lang=lang;lastWave=-1;updateUI();}
function selectHero(id){selected=id;tool='move';renderer.selected=id;renderer.tool=tool;updateUI();}
function selectTool(id){tool=tool===id?'move':id;renderer.tool=tool;updateUI();if(tool!=='move')toast(t(BUILDINGS[tool].desc));}
function updateUI(){const s=game.state,h=s.heroes.find(a=>a.id===selected),base=HEROES.find(a=>a.id===selected);$('core-hp').textContent=Math.ceil(s.core.hp);$('gold').textContent=Math.floor(s.gold);$('level').textContent=s.level;$('pause-overlay').hidden=!paused;$('pause').textContent=paused?'▶':'Ⅱ';$('skill-name').textContent=t(base.skill);$('skill-cooldown').textContent=h.cool>0?`${Math.ceil(h.cool)}s`:'E';$('skill').disabled=s.phase!=='battle'||h.hp<=0||h.cool>0||paused;$('skill').classList.toggle('active',tool==='skill');$('selection-tip').textContent=t(['選英雄後點地面移動','Select hero, then tap ground']);
 for(const el of $('party').children){const hero=s.heroes.find(a=>a.id===el.dataset.hero);el.classList.toggle('active',hero.id===selected&&['move','skill'].includes(tool));el.classList.toggle('dead',hero.hp<=0);el.querySelector('.mini-hp i').style.width=`${Math.max(0,hero.hp/game.stats(hero).hp)*100}%`;el.setAttribute('aria-pressed',String(hero.id===selected));}
 for(const el of $('build-tools').children){el.classList.toggle('active',tool===el.dataset.tool);el.setAttribute('aria-pressed',String(tool===el.dataset.tool));el.disabled=!['prep','battle'].includes(s.phase)||paused;}
 const phaseText=s.phase==='battle'?t(['防守中','DEFENDING']):t(['整備時間','PREPARATION']);$('phase-label').textContent=`${phaseText} · ${Math.min(s.phase==='battle'?s.wave:s.wave+1,12)} / 12`;
 const wave=WAVES[Math.min(s.phase==='battle'?s.wave-1:s.wave,11)];$('wave-title').textContent=t(wave.name);$('forecast').textContent=t(wave.hint);
 if(lastWave!==s.wave||lastHUDPhase!==s.phase){$('wave-dots').innerHTML=WAVES.map((w,i)=>`<i class="${w.boss?'boss ':''}${i<s.wave-(s.phase==='battle'?1:0)?'done':i===(s.phase==='battle'?s.wave-1:s.wave)?'current':''}"></i>`).join('');lastWave=s.wave;lastHUDPhase=s.phase;}
 $('next-wave').disabled=!loaded||paused||!['prep','battle'].includes(s.phase);$('next-wave').textContent=!loaded?tr('loading'):s.phase==='battle'?`${t(['戰鬥速度','Battle speed'])} · ${speed}×`:`${t(['迎戰第','Begin wave'])} ${Math.min(s.wave+1,12)} ${t(['波',''])} →`;
 $('action-note').textContent=s.phase==='battle'?`${t(['剩餘敵人','Enemies left'])} ${s.enemies.length+s.queue.length} · ${t(['可隨時建造與維修','Keep building and repairing'])}`:t(['先佈置防線 · Space 開戰 · 拖曳平移／雙指縮放','Build first · Space to begin · Drag to pan / pinch to zoom']);
 const boss=s.enemies.find(e=>e.boss);$('boss-bar').hidden=!boss;if(boss){$('boss-bar').querySelector('span').textContent=`${t(boss.name)}${boss.enraged?t([' · 狂暴',' · Enraged']):''}`;$('boss-bar').querySelector('progress').value=boss.hp/boss.maxHp*100;}
}
function showDialog(id){if(!$(id).open)$(id).showModal();}function modalOpen(){return !!document.querySelector('dialog[open]');}
function statsText(g){const labels={atk:['攻擊','ATK'],hp:['生命','HP'],armor:['護甲','Armor'],range:['射程','Range'],haste:['攻速','Haste'],heal:['治療','Healing'],cdr:['冷卻縮減','CDR']};return Object.entries(g.stats).map(([k,v])=>`${t(labels[k])} +${['haste','heal','cdr'].includes(k)?`${Math.round(v*100)}%`:v}`).join(' · ');}
function targetButtons(container,callback){$(container).innerHTML=HEROES.map(h=>`<button data-target="${h.id}" class="${h.id===selected?'active':''}">${t(h.name)} · ${t(h.job)}</button>`).join('');$(container).querySelectorAll('button').forEach(b=>b.onclick=()=>{selected=b.dataset.target;renderer.selected=selected;callback();});}
function showLoot(){const s=game.state;$('loot-title').textContent=s.wave%4===0?t(['傳說，從這裡開始。','A legend starts here.']):t(['又守住了一波。','Another wave held.']);$('loot-summary').textContent=lang==='zh'?`第 ${s.wave} 波完成 · +${WAVES[s.wave-1].reward} 金幣 · 小隊 Lv.${s.level}。選一件裝備；通用裝備交給下方選中的英雄。`:`Wave ${s.wave} cleared · +${WAVES[s.wave-1].reward} gold · Party Lv.${s.level}. Pick one item. Universal items go to your selected hero.`;targetButtons('loot-targets',showLoot);$('loot-cards').innerHTML=s.reward.map(id=>{const g=GEAR.find(a=>a.id===id),who=g.who==='all'?selected:g.who,hero=HEROES.find(h=>h.id===who),rarity=RARITIES[g.tier-1];return `<article class="loot-card" style="--rarity:${rarity[2]}"><img src="${thumb(hero.sprite)}" alt=""><small>${t(rarity)} · ${t(SLOTS[g.slot])}</small><h3>${t(g.name)}</h3><div class="stats">${statsText(g)}</div><p>${t(g.desc)}</p><button data-loot="${id}" data-recipient="${who}">${t(['裝備給','Equip on'])} ${t(hero.name)}</button></article>`;}).join('');$('loot-cards').querySelectorAll('button').forEach(b=>b.onclick=()=>{const g=GEAR.find(a=>a.id===b.dataset.loot);if(game.chooseLoot(g.id)){game.equip(g.id,b.dataset.recipient);$('loot-dialog').close();selectHero(b.dataset.recipient);save();chime('loot');toast(`${t(g.name)} · ${t(g.desc)}`);updateUI();}});showDialog('loot-dialog');}
function showBag(){targetButtons('bag-party',showBag);const s=game.state,h=s.heroes.find(a=>a.id===selected),st=game.stats(h);$('hero-stats').textContent=`HP ${Math.round(st.hp)} · ATK ${Math.round(st.atk)} · ${t(['護甲','Armor'])} ${st.armor} · ${t(['射程','Range'])} ${st.range.toFixed(1)}`;$('equipped').innerHTML=Object.entries(SLOTS).map(([slot,label])=>{const g=GEAR.find(g=>g.id===h.gear[slot]);return`<div><small>${t(label)}</small><b>${g?t(g.name):t(['旅行者的初始裝備','Traveler’s starter gear'])}</b><p>${g?t(g.desc):'—'}</p></div>`;}).join('');$('bag-items').innerHTML=s.bag.length?s.bag.map((id,i)=>{const g=GEAR.find(g=>g.id===id),allowed=g.who==='all'||g.who===selected;return`<div class="bag-item"><div><b style="color:${RARITIES[g.tier-1][2]}">${t(g.name)}</b><p>${statsText(g)}<br>${t(g.desc)}</p></div><button data-equip="${id}" ${s.phase!=='prep'||!allowed?'disabled':''}>${t(['裝備','Equip'])}</button><button data-salvage="${id}" ${s.phase!=='prep'?'disabled':''}>${t(['分解','Salvage'])} +${g.tier*10}</button></div>`;}).join(''):`<p>${t(['背包還是空的。守住第一波就能拿到裝備。','Your bag is empty. Clear a wave to find gear.'])}</p>`;$('bag-items').querySelectorAll('[data-equip]').forEach(b=>b.onclick=()=>{if(game.equip(b.dataset.equip,selected)){save();showBag();chime('loot');}});$('bag-items').querySelectorAll('[data-salvage]').forEach(b=>b.onclick=()=>{if(game.salvage(b.dataset.salvage)){save();showBag();chime();}});showDialog('bag-dialog');updateUI();}
function showResult(){const s=game.state,won=s.phase==='victory';storage.remove(SAVE);$('result-kicker').textContent=won?'DAWN RETURNS TO THE FOREST':'EVERY DEFENSE TELLS A STORY';$('result-title').textContent=t(won?['你守住了，森林的黎明。','You brought dawn to the forest.']:['水晶熄滅了，冒險還沒結束。','The crystal fades. Your story goes on.']);$('result-summary').textContent=lang==='zh'?`守到第 ${s.wave} 波 · 擊敗 ${s.kills} 隻敵人 · 建造 ${s.totalBuilt} 座設施 · 小隊 Lv.${s.level}`:`Reached wave ${s.wave} · ${s.kills} enemies defeated · ${s.totalBuilt} structures built · Party Lv.${s.level}`;$('result-heroes').innerHTML=s.heroes.map(h=>`<div><img src="${thumb(h.sprite)}" alt="${t(HEROES.find(a=>a.id===h.id).name)}"><small>${h.kills} ${t(['擊殺','kills'])}</small></div>`).join('');showDialog('result-dialog');chime('loot');}
const errors={gold:['金幣不足，擊敗敵人或分解裝備可取得。','Not enough gold. Defeat enemies or salvage gear.'],route:['要留一條路！這裡會封死敵人的通路。','Leave a route open. This would seal the path.'],occupied:['這格有人或建築，換個位置吧。','That tile is occupied. Try another.'],tile:['這裡不能建造。入口、岩石與水晶要保持淨空。','Keep gates, rocks and the crystal clear.'],phase:['等下一次整備再操作。','Wait until the next preparation phase.'],building:['請點選一座建築。','Select a building.'],full:['耐久已滿。','Already at full health.'],max:['已經是最高三級。','Already at maximum level 3.']};
function command(x,y){if(!loaded||renderer.lost||paused||modalOpen())return;const s=game.state;if(tool==='skill'){if(game.skill(selected,x,y)){chime('skill');tool='move';renderer.tool=tool;}else toast(t(['這裡無法施放技能。','Cannot cast here.']));}else if(['wall','tower','frost'].includes(tool)){const r=game.build(tool,x,y);if(r.ok){chime('build');save();}else toast(t(errors[r.error]||['無法建造','Cannot build']));}else if(['repair','upgrade','sell'].includes(tool)){const r=game.interact(tool,x,y);if(r.ok){chime('build');save();}else toast(t(errors[r.error]||['無法操作','Cannot do that']));}else{const e=s.enemies.filter(e=>e.hp>0&&distance(e,{x,y})<.9).sort((a,b)=>distance(a,{x,y})-distance(b,{x,y}))[0];if(e){s.focus=e.id;toast(t(['全隊集火！','Focus fire!']));}else if(game.moveHero(selected,x,y)){chime();save();}else toast(t(['請選擇空地。倒下的英雄會在波次結束復原。','Choose clear ground. Fallen heroes recover between waves.']));}updateUI();}
function cast(){const h=game.state.heroes.find(a=>a.id===selected);if($('skill').disabled)return;if(['knight','priest'].includes(selected)){if(game.skill(selected,h.x,h.y))chime('skill');}else{tool='skill';renderer.tool=tool;toast(t(['點戰場選擇技能落點。','Tap the battlefield to aim your skill.']));}updateUI();}
function next(){if(!loaded||renderer.lost||paused||modalOpen())return;if(game.state.phase==='battle'){speed=speed===1?2:1;}else{save();if(game.start()){tool='move';renderer.tool=tool;chime();}}updateUI();}
function pause(value=!paused){if(modalOpen()||renderer.lost)return;paused=value;updateUI();}
$('party').onclick=e=>{const b=e.target.closest('[data-hero]');if(b)selectHero(b.dataset.hero);};$('build-tools').onclick=e=>{const b=e.target.closest('[data-tool]');if(b&&!b.disabled)selectTool(b.dataset.tool);};$('skill').onclick=cast;$('next-wave').onclick=next;$('pause').onclick=()=>pause();$('resume').onclick=()=>pause(false);$('inventory').onclick=showBag;$('help').onclick=()=>showDialog('intro');$('begin').onclick=()=>{$('intro').close();chime();toast(restored?t(['已接續最近的整備點。','Resumed your latest checkpoint.']):t(['先在路旁蓋箭塔，再迎戰第一波。','Build an arrow tower beside the road, then start wave one.']));};
$('lang').onclick=()=>{lang=lang==='zh'?'en':'zh';pref();staticUI();if($('loot-dialog').open)showLoot();if($('bag-dialog').open)showBag();};$('sound').onclick=()=>{sound=!sound;pref();chime();staticUI();};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());$('loot-dialog').addEventListener('cancel',e=>e.preventDefault());$('result-dialog').addEventListener('cancel',e=>e.preventDefault());
function newRun(){game=new Game();storage.remove(SAVE);$('result-dialog').close();paused=false;speed=1;lastPhase='';lastWave=-1;lastKills=0;selectHero('knight');renderer.resetCamera(true);save();updateUI();}
$('new-run').onclick=newRun;
$('restart').onclick=()=>showDialog('restart-dialog');
$('restart-confirm').onclick=()=>{for(const d of document.querySelectorAll('dialog[open]'))d.close();newRun();};
function zoom(delta){renderer.zoom=Math.max(.65,Math.min(2.8,renderer.zoom*delta));} $('zoom-in').onclick=()=>zoom(1.2);$('zoom-out').onclick=()=>zoom(1/1.2);$('fit').onclick=()=>renderer.resetCamera();
$('rotate-left').onclick=()=>renderer.rotate?.(-Math.PI/4);$('rotate-right').onclick=()=>renderer.rotate?.(Math.PI/4);
for(const id of ['rotate-left','rotate-right'])$(id).hidden=renderer.backend!=='three';
const pointers=new Map();let gesture=null;const field=$('field');function local(e){const r=field.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top};}field.addEventListener('pointerdown',e=>{if(!loaded||renderer.lost||modalOpen()||paused||e.button!==0)return;field.focus({preventScroll:true});field.setPointerCapture(e.pointerId);const p=local(e);pointers.set(e.pointerId,p);if(pointers.size===1)gesture={start:p,last:p,moved:false,pan:{...renderer.pan}};else{const[a,b]=[...pointers.values()];gesture={pinch:Math.hypot(a.x-b.x,a.y-b.y),zoom:renderer.zoom,moved:true};}});
field.addEventListener('pointermove',e=>{const p=local(e);renderer.hover=renderer.unproject(p.x,p.y);if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,p);if(pointers.size>1){const[a,b]=[...pointers.values()];if(gesture?.pinch)renderer.zoom=Math.max(.65,Math.min(2.8,gesture.zoom*Math.hypot(a.x-b.x,a.y-b.y)/gesture.pinch));}else if(gesture?.start){const dx=p.x-gesture.start.x,dy=p.y-gesture.start.y;if(Math.hypot(dx,dy)>7)gesture.moved=true;if(gesture.moved)renderer.pan={x:gesture.pan.x+dx,y:gesture.pan.y+dy};}});
field.addEventListener('pointerup',e=>{const p=local(e);if(pointers.has(e.pointerId)&&gesture&&pointers.size===1&&!gesture.moved&&!paused&&!modalOpen()&&!renderer.lost){const actor=tool==='move'?renderer.pickActor(game.state,p.x,p.y):null;if(actor?.type==='hero')selectHero(actor.id);else if(actor?.type==='enemy'){game.state.focus=actor.id;toast(t(['全隊集火！','Focus fire!']));}else{const tile=renderer.unproject(p.x,p.y);command(tile.x,tile.y);}}pointers.delete(e.pointerId);if(field.hasPointerCapture(e.pointerId))field.releasePointerCapture(e.pointerId);if(!pointers.size)gesture=null;});field.addEventListener('pointercancel',()=>{pointers.clear();gesture=null;});field.addEventListener('pointerleave',()=>{if(!pointers.size)renderer.hover=null;});field.addEventListener('wheel',e=>{e.preventDefault();zoom(e.deltaY<0?1.08:1/1.08);},{passive:false});field.addEventListener('contextmenu',e=>{e.preventDefault();tool='move';renderer.tool=tool;updateUI();});
document.addEventListener('keydown',e=>{if(modalOpen())return;if(e.repeat){e.preventDefault();return;}if(e.target.closest('button,a,input,select')&&[' ','Enter'].includes(e.key))return;const k=e.key.toLowerCase();if(k==='p'||k==='escape'){e.preventDefault();if(tool!=='move'&&k==='escape'){tool='move';renderer.tool=tool;updateUI();}else pause();return;}if(paused||renderer.lost||!loaded)return;if(k==='['||k===']'){renderer.rotate?.((k==='['?-1:1)*Math.PI/4);return;}if(['1','2','3','4'].includes(k)){selectHero(HEROES[+k-1].id);return;}const keys={b:'wall',t:'tower',f:'frost',r:'repair',u:'upgrade',x:'sell'};if(keys[k]){selectTool(keys[k]);return;}if(k==='e'){cast();return;}if(k===' '){e.preventDefault();next();return;}if(k==='i'){showBag();return;}if(['arrowup','arrowdown','arrowleft','arrowright','enter'].includes(k)){e.preventDefault();renderer.hover??={...CORE};if(k==='enter')command(renderer.hover.x,renderer.hover.y);else{const moves={arrowup:[0,-1],arrowdown:[0,1],arrowleft:[-1,0],arrowright:[1,0]},[dx,dy]=moves[k];renderer.hover={x:Math.max(0,Math.min(W-1,renderer.hover.x+dx)),y:Math.max(0,Math.min(H-1,renderer.hover.y+dy))};}}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&game.state.phase==='battle'){paused=true;updateUI();}});window.addEventListener('blur',()=>{if(game.state.phase==='battle'){paused=true;updateUI();}});matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',e=>renderer.reduced=e.matches);const resizeObserver=new ResizeObserver(()=>renderer.resize());resizeObserver.observe(field);renderer.resize();renderer.tool=tool;
field.addEventListener('forest-context',e=>{paused=true;updateUI();toast(t(e.detail.lost?['畫面暫時中斷，已暫停戰鬥。正在恢復…','Display interrupted. Battle paused while recovering…']:['畫面已恢復。按繼續守城接著玩。','Display restored. Resume when ready.']));});
window.addEventListener('pagehide',e=>{if(!e.persisted){resizeObserver.disconnect();renderer.dispose?.();}});
let previous=performance.now();function frame(now){const elapsed=Math.min(.1,(now-previous)/1000);previous=now;if(loaded&&!renderer.lost&&!paused&&!modalOpen()){let remaining=elapsed*speed;while(remaining>0){const step=Math.min(1/60,remaining);game.tick(step);remaining-=step;}}if(loaded)renderer.draw(game,paused||modalOpen()?0:elapsed);if(game.state.phase!==lastPhase){lastPhase=game.state.phase;if(lastPhase==='reward'){save();showLoot();}else if(['victory','defeat'].includes(lastPhase))showResult();updateUI();}if(now-uiTime>100){uiTime=now;updateUI();}if(game.state.kills>lastKills){lastKills=game.state.kills;if(lastKills%3===0)chime();}if(now>toastUntil)$('toast').classList.remove('show');requestAnimationFrame(frame);}
try{await renderer.load();loaded=true;staticUI();if(game.state.phase==='reward'){showLoot();lastPhase='reward';}else{showDialog('intro');if(restored)$('begin').textContent=t(['接續這次冒險','Continue this adventure']);}save();requestAnimationFrame(frame);}catch(error){console.error(error);$('next-wave').textContent=t(['素材讀取失敗，點此重試','Assets failed to load. Retry']);$('next-wave').disabled=false;$('next-wave').onclick=()=>location.reload();toast(t(['請確認網路後重試。','Check your connection and retry.']));}
// Read-only diagnostics for reproducible QA; no state mutation or resource injection.
Object.defineProperty(window,'crystalGuard',{value:Object.freeze({snapshot:()=>game.snapshot(),project:(x,y)=>renderer.project(x,y),assets:()=>({loaded,frames:renderer.frames.length,environment:!!renderer.environment}),ui:()=>({selected,tool,paused,speed,zoom:renderer.zoom,azimuth:renderer.azimuth}),render:()=>renderer.diagnostics()}),writable:false});
